# apiVersion: v1
# kind: Namespace
#metadata:
#  name: ncm-cert
# ---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ncm-cert
  namespace: ncm-issuer
  # namespace: ncm-cert
spec:
  dnsNames:
    - foo.bar.local
  renewBefore: 120h
  secretName: mysecret-secret
  privateKey:
    rotationPolicy: Always
  issuerRef:
    group: certmanager.ncm.nokia.com
    kind: Issuer
    name: ncm
