apiVersion: v1
entries:
  ncm-issuer:
  - apiVersion: v1
    appVersion: 1.1.0
    created: "2023-10-27T16:42:38.921615933Z"
    description: A Helm chart for cert-manager external issuer with NCM (NetGuard
      Certificate Manager)
    digest: 368a82b7de9067a130b9f204457de7c48f80052b39bb957800b7a25630e7138f
    home: https://github.com/nokia/ncm-issuer
    icon: https://i.imgur.com/G2p0BwS.png
    keywords:
    - ncm-issuer
    - cert-manager
    - com.nokia.ncm.certifier
    - tls
    kubeVersion: '>= 1.18.0-0 < 1.28.0-0'
    maintainers:
    - email: sara.ryfczynska@nokia.com
      name: Sara Ryfczynska
    - email: dawid.machoczek@nokia.com
      name: Dawid Machoczek
    - email: adam.korba@nokia.com
      name: Adam Korba
    name: ncm-issuer
    sources:
    - https://github.com/nokia/ncm-issuer
    urls:
    - ncm-issuer-1.1.0.tgz
    version: 1.1.0
generated: "2023-10-27T16:42:38.920427129Z"
