apiVersion: v1
entries:
  ncm-issuer:
  - apiVersion: v1
    appVersion: 1.1.0
    created: "2023-10-27T15:48:11.560344395Z"
    description: A Helm chart for cert-manager external issuer with NCM (NetGuard
      Certificate Manager)
    digest: d2da6e4f9c42e1959d4cc9534c3e5c5bbc3b1edff155f84c5b29133b5b00c8ee
    home: https://github.com/nokia/ncm-issuer
    icon: https://i.imgur.com/G2p0BwS.png
    keywords:
    - ncm-issuer
    - cert-manager
    - com.nokia.ncm.certifier
    - tls
    kubeVersion: '>= 1.18.0-0 < 1.28.0-0'
    maintainers:
    - email: sara.ryfczynska@nokia.com
      name: Sara Ryfczynska
    - email: dawid.machoczek@nokia.com
      name: Dawid Machoczek
    - email: adam.korba@nokia.com
      name: Adam Korba
    name: ncm-issuer
    sources:
    - https://github.com/nokia/ncm-issuer
    urls:
    - ncm-issuer-1.1.0.tgz
    version: 1.1.0
generated: "2023-10-27T15:48:11.559394095Z"
