name: e2e tests

on:
  push:
  pull_request:

jobs:
  find-ca-test:
    name: "find CA by href or name and enroll"
    uses: ./.github/workflows/find-ca-and-enroll-tests.yml

  pkey-test:
    name: "pkey tests"
    uses: ./.github/workflows/pkey-tests.yml

  san-test:
    name: "san test"
    uses: ./.github/workflows/san-test.yml

  client-auth-test:
    name: "client auth test"
    uses: ./.github/workflows/clientauth-test.yml

  enrollment-and-renewal-test:
    name: "enrollment and renewal tests"
    uses: ./.github/workflows/enrollment-and-renewal-tests.yml