name: e2e tests

on:
  push:
  pull_request:

jobs:
  find-ca-test:
    uses: ./.github/workflows/e2e/find-ca-and-enroll-tests.yml

  pkey-test:
    uses: ./.github/workflows/e2e/pkey-tests.yml

  san-test:
    uses: ./.github/workflows/e2e/san-test.yml

  client-auth-test:
    uses: ./.github/workflows/e2e/clientauth-test.yml

  enrollment-and-renewal-test:
    uses: ./.github/workflows/e2e/enrollment-and-renewal-tests.yml