name: e2e tests

on:
  workflow_run:
    workflows: [tests]
    types:
      - completed

jobs:
  find-ca-test:
    steps:
      - uses: actions/checkout@v3
      - name: "find CA by href or name and enroll"
        uses: ./.github/workflows/e2e/find-ca-and-enroll-tests.yml

  pkey-test:
    steps:
      - uses: actions/checkout@v3
      - name: "pkey tests"
        uses: ./.github/workflows/e2e/pkey-tests.yml

  san-test:
    steps:
      - uses: actions/checkout@v3
      - name: "san test"
        uses: ./.github/workflows/e2e/san-test.yml

  client-auth-test:
    steps:
      - uses: actions/checkout@v3
      - name: "client auth test"
        uses: ./.github/workflows/e2e/clientauth-test.yml

  enrollment-and-renewal-test:
    steps:
      - uses: actions/checkout@v3
      - name: "enrollment and renewal tests"
        uses: ./.github/workflows/e2e/enrollment-and-renewal-tests.yml