name: unit tests using different go version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.16', '1.16.15', '1.17', '1.17.8', '1.18.9', '1.19.6']
    steps:
    - name: "Checkout git"
      uses: actions/checkout@v3

    - name: "Setup Go"
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: "Install dependencies"
      run: go get .

    - name: "Test with Go"
      run: go test ./... -json > unit-test-results-${{ matrix.go-version }}.json

    - name: "[ * ] Collecting unit test results"
      if: ${{ failure() }}
      run: |
        mkdir -p ${{ github.workspace }}/artifact/upload
        sudo cp -rp *.json ${{ github.workspace }}/artifact/data/
        sudo tar -C ${{ github.workspace }}/artifact/ -czf ${{ github.workspace }}/artifact/upload/artifact.tar.gz

    - name: "[ * ] Uploading artifacts"
      uses: actions/upload-artifact@v3
      if: ${{ failure() }}
      with:
        name: unit-test-results-${{ matrix.go-version }}.tar.gz
        path: ${{ github.workspace }}/artifact/upload/
